### ISSUE TITLE
proposal: support multiple transformers

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#281]
Implement the **support** for **multiple transformers**.

A *transformer* is a concept which includes both the platform where the transformer runs (Lambda, local compiler, etc…) as well as the runtime (Node, Python, etc…).

### In the configuration

It should be possible to specify zero, one or more transformers in the `config.yaml` file, with a syntax like:

```yaml
transformers:
    -
        id: node-lambda
        name: "Node (on Lambda)"
        lambda:
            # lambda specific settings
    -
        id: python-lambda
        name: "Python (on Lambda)"
        lambda:
            # lambda specific settings
    -
        id: local-python
        name: "Python (local)"
        localPython:
            # local Python specific settings
```

So, every *transformer* under `transformers` should provide:

* an `id`, which is used internally by Chichi to identify a transformer
* a `name`, which is shown in the UI and thus can be changed at any time
* a transformer-specific setting, declared, for example, with a key `lambda` or `localPython`… It is an error to specify more than one transformer-specific setting.

### Workspace behaviour

Every workspace can limit the transformers available in it.

### Action behavior

Every action, when created and/or modified, can choose which transformer to use (from the set of transformers available in its workspace).
